services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"
    env_file:
<<<<<<< HEAD
      - .env.devcontainer
=======
      - ../.env
>>>>>>> 64ecdf2 (core: add devcontainer)
    command: sleep infinity
    network_mode: host

volumes:
  node_modules:
